apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vetcare-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: vetcare.local
      http:
        paths:
          # Frontend routes - serve the main application
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fe-service
                port:
                  number: 80
          # Backend API routes
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: laravel-service
                port:
                  number: 80
